### ISSUE TITLE
no module named 'mrcnn'

### ISSUE THREAD

**Issue by nafri1305** [haochen23/fine-tune-MaskRcnn#2]
i am very new to python and google colab, and i have gotten this error when running step 5 based on your article.

_____
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-cc59d5e6eecf> in <module>()
     12 import matplotlib.patches as patches
     13 ROOT_DIR = os.path.abspath("../")
---> 14 from mrcnn import utils
     15 from mrcnn import visualize
     16 from mrcnn.visualize import display_images

ModuleNotFoundError: No module named 'mrcnn'
_____

i have not started to use my own dataset yet, just running with the provided beagle data to see how it works
what are my options to solve this?

**Comment by ApoorvaOjha** [comment]
hey , how did you solve this?

**Comment by nafri1305** [comment]
i had to change the directory before running the 5th step (based on [his article](https://haochen23.github.io/2020/06/fine-tune-mask-rcnn.html#.YBNmIugzZPZ)). if youre on google colab as well, try inserting
`%cd /content/Mask_RCNN` before the line 
`%matplotlib inline` in the beginning of step 5

**Comment by ApoorvaOjha** [comment]
> i had to change the directory before running the 5th step (based on [his article](https://haochen23.github.io/2020/06/fine-tune-mask-rcnn.html#.YBNmIugzZPZ)). if youre on google colab as well, try inserting
> `%cd /content/Mask_RCNN` before the line
> `%matplotlib inline` in the beginning of step 5

Thank you very much for the reply , it worked for me as well!
